name: nitro

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: nitro-bot
    env:
      NODE_ENV: "production"
    depends_on:
  
  jobs:
    build:
      context: .
      dockerfile: Dockerfile.job
    container_name: nitro-jobs
    env:
      NODE_ENV: "production"
