name: nitro

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: nitro-bot
    environment:
      NODE_ENV: "production"
    restart: always

  jobs:
    build:
      context: .
      dockerfile: Dockerfile.job
    container_name: nitro-jobs
    environment:
      NODE_ENV: "production"
    restart: always
