name: viper

services:
  database:
    image: mongo
    container_name: viper-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:8.0-alpine
    container_name: viper-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: viper-bot
    env_file:
      - .env
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
  
  jobs:
    build:
      context: .
      dockerfile: Dockerfile.job
    container_name: viper-jobs
    env_file:
      - .env
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    depends_on:
      redis:
        condition: service_started
      bot:
        condition: service_started

volumes:
  mongo-data:
  redis-data:
