services:
  - type: worker
    name: nitro-bot
    runtime: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./Dockerfile.bot
    envVars:
      - fromGroup: nitro-launch
  
  - type: worker
    name: nitro-jobs
    runtime: docker
    plan: standard
    region: frankfurt
    dockerfilePath: ./Dockerfile.job
    envVars:
      - fromGroup: nitro-launch